// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC11ifMa2Z60tc-DhAbZRPJrqe56Z6CHcc',
    appId: '1:41586208567:web:d6fc108ff637187a7234b2',
    messagingSenderId: '41586208567',
    projectId: 'flutter-app-aab61',
    authDomain: 'flutter-app-aab61.firebaseapp.com',
    storageBucket: 'flutter-app-aab61.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF22hWzuswrq-A5F4fPwKXptUMkyP9gSE',
    appId: '1:41586208567:android:d691fd5cb0a5dfcb7234b2',
    messagingSenderId: '41586208567',
    projectId: 'flutter-app-aab61',
    storageBucket: 'flutter-app-aab61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChEQMXekG9tkVZkdr2BRli7lvLnSP1_Vw',
    appId: '1:41586208567:ios:0aa51854214dde017234b2',
    messagingSenderId: '41586208567',
    projectId: 'flutter-app-aab61',
    storageBucket: 'flutter-app-aab61.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChEQMXekG9tkVZkdr2BRli7lvLnSP1_Vw',
    appId: '1:41586208567:ios:0aa51854214dde017234b2',
    messagingSenderId: '41586208567',
    projectId: 'flutter-app-aab61',
    storageBucket: 'flutter-app-aab61.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC11ifMa2Z60tc-DhAbZRPJrqe56Z6CHcc',
    appId: '1:41586208567:web:e20343abde07fe2e7234b2',
    messagingSenderId: '41586208567',
    projectId: 'flutter-app-aab61',
    authDomain: 'flutter-app-aab61.firebaseapp.com',
    storageBucket: 'flutter-app-aab61.firebasestorage.app',
  );
}
